### ISSUE TITLE
Trace feature

### ISSUE THREAD

**Issue by ghost** [jim11662418/EPROM-Emulator#1]
Hello,
Would be possible to add support for larger eprom like 27512?
And would be possible  to add "trace" feature  whitout lose performance?

**Comment by jim11662418** [comment]
> Hello, Would be possible to add support for larger eprom like 27512? And would be possible to add "trace" feature whitout lose performance?

The IDT7134 Dual Port RAM is only 4K.  To emulate an EPROM like the 27512 you'd need 16  dual port RAMs. Maybe do-able, but outside the scope of a simple project such as this. To emulate large EPROMs, I use [this](https://mygeekyhobby.com/) and recommend it.
